[jobs.miniplc0-tokenize]
build = {source = "dockerfile", path = "."}
run = [
  "./miniplc0 -t $input -o $output",
]

[jobs.miniplc0-analyse]
build = {source = "dockerfile", path = "."}
run = [
  "./miniplc0 -a $input -o $output",
]
